callbacks:
   model_checkpoint:
      save_best_only: true
      monitor: val_loss
      patience: 5
      save_weights_only: True
      mode: min

   scheduler:
      monitor: loss
      factor: 0.5
      patience: 10

data:
  train_set_path: /home/miguelmartins/Datasets/kvasir-seg/Kvasir-SEG/
  validation_set_path: /home/miguelmartins/Datasets/kvasir-seg/Kvasir-SEG/
  test_set_path: /home/miguelmartins/Datasets/kvasir-seg/Kvasir-SEG/
  target_size: [512, 512]
  n_classes: 9

model:
  level_depth: [32, 64, 128, 256]

training:
  batch_size: 16
  epochs: 400
  learning_rate: 0.0001
  loss: weighted_multi
  optimizer: adam
  metrics: baseline
